### ISSUE TITLE
Fehler in Artikel "Xbox One Controller blockiert Maus- und Tastatureingaben"

### ISSUE THREAD

**Issue by telmi51** [MarvinMenzerath/menzerath.eu#2]
URL: https://menzerath.eu/artikel/xbox-one-controller-blockiert-eingaben/

Hallo,

der 3. Punkt (Laden Sie die Treiber von dieser Seite herunter und entpacken Sie das Archiv an einen beliebigen Ort)

..hier funktioniert leider der Downloadlink nicht, könnten sie einen neuen link online stellen? :/

lieben gruß

**Comment by MarvinMenzerath** [comment]
Ich habe den Link gerade ausprobiert und nach dem Laden des OneDrive-Verzeichnisses hat der Download sofort begonnen...
